services:
  api:
    build:
      context: .
      dockerfile: back/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=12345
      - DATABASE_NAME=genn
      - DATABASE_USERNAME=tony

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=genn
      - POSTGRES_USER=tony
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

  frontend:
    build:
      context: .
      dockerfile: front/Dockerfile
    container_name: frontend
    depends_on:
      - api
    ports:
      - "5173:5173"

volumes:
  postgres-db:
